Change `has` to return false for empty values
fiverr/i18n.js pull request #89
Opened 2023-08-13 10:01 UTC by alonfixlerfiverr

2023-08-14 06:58 UTC, ilsavin-fiverr approved these changes

2023-08-14 08:44 UTC, raphaelboukara commented on index.js
> +        return typeof result !== 'undefined' && !EMPTY_VALUES.includes(result);
`return !EMPTY_VALUES.includes(result);` + add undefined to `EMPTY_VALUES` won't work?

2023-08-14 08:44 UTC, raphaelboukara approved these changes

2023-08-14 08:45 UTC, alonfixlerfiverr commented on index.js
> +        return typeof result !== 'undefined' && !EMPTY_VALUES.includes(result);
I rather not change `EMPTY_VALUES` definition as it'll have other implications.

2023-08-14 10:01 UTC, omrilotan requested changes
This is a non-compatible change in the interface - the return value of a method is explicitly changing. I don't feel the version update reflects this.

If you want to prevent from incrementing a major version - you could add a new flag and release a minor version.

```js
const i18n = new I18n({
  ...
  tolerateEmptyValues: false
});
```

In this example, `tolerateEmptyValues` will default to `true`, so it won't be changing the existing behaviour for anyone who doesn't explicitly mentions they want to treat empty values as missing values.

2023-08-15 07:52 UTC, alonfixlerfiverr commented
> This is a non-compatible change in the interface - the return value of a method is explicitly changing. I don't feel the version update reflects this.
> 
> If you want to prevent from incrementing a major version - you could add a new flag and release a minor version.
> 
> ```js
> const i18n = new I18n({
>   ...
>   tolerateEmptyValues: false
> });
> ```
> 
> In this example, `tolerateEmptyValues` will default to `true`, so it won't be changing the existing behaviour for anyone who doesn't explicitly mentions they want to treat empty values as missing values.

@omrilotan While I understand your point I look at it differently: To me it seems like a bug because the point of the `has` method is to check if a translation exists usually before applying the `translate` method. If we consider empty values as not translated then `has` must take it into account as well. From a consumer point of view it doesn't make sense that `has` will return false for missing translation in English and false for the other locales.

Due to the above I rather go with my approach even if it changes behaviour of the module (which is something you can say probably about each bug fix). I understand this was done in a concise way but I still think this is a bug. Bumping a major or adding a config as a minor is an overkill in this case and aren't worth the price of it.

2023-08-15 08:10 UTC, omrilotan approved these changes
Since the "has" function hints on the translation object behaving similarly to a Map, having an empty value returns "true".

Because the documentation explicitly mentions this behaviour (including empty strings) this can not be considered as a bug, but I can agree it may be a design flaw.

I'll give another option for your consideration, add a "hasValue" helper function that does exactly what you want (minor version).

It's up to you how you would like to release this changeset, just remember this is OSS.

2023-08-15 09:58 UTC, alonfixlerfiverr commented
> Since the "has" function hints on the translation object behaving similarly to a Map, having an empty value returns "true".
> 
> Because the documentation explicitly mentions this behaviour (including empty strings) this can not be considered as a bug, but I can agree it may be a design flaw.
> 
> I'll give another option for your consideration, add a "hasValue" helper function that does exactly what you want (minor version).
> 
> It's up to you how you would like to release this changeset, just remember this is OSS.

Tnx. I've thought about `hasValue` but I decided not to go with it for the same reasons I've mentioned above.

2023-08-15 09:59 UTC, merged